### ISSUE TITLE
width for each cell

### ISSUE THREAD

**Issue by maryamfekri** [Morbix/CloudTagView#1]
how can i find out the exact width size for each tag ?? 
this code : normalTag.intrinsicContentSize() 
returns  {-1,-1}

how can i find it out ?

**Comment by Morbix** [comment]
Hi @maryamfekri , I've just release a new version for you: **1.0.2**

Try:

``` swift
let tag = TagView(text: "Adding new tag")
print(tag.frame)
```

**Comment by Morbix** [comment]
Another observation: 

> UIView and NSView don't have intrinsic content size.

https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/AutolayoutPG/AnatomyofaConstraint.html#//apple_ref/doc/uid/TP40010853-CH9-SW21
