### ISSUE TITLE
How to add remove 'x' ?

### ISSUE THREAD

**Issue by deepak475121** [Morbix/CloudTagView#10]
i tried to remove added tags but how can i add the 'X' for remove tags

**Comment by Morbix** [comment]
The "x" is default. Could you explain more?

Enviado do meu iPhone

Em 29 de dez de 2016, ?s 05:52, Deepakkumar <notifications@github.com<mailto:notifications@github.com>> escreveu:


i tried to remove added tags but how can i add the 'X' for remove tags

-

**Comment by deepak475121** [comment]
i got it...... thank you for respons

**Comment by Morbix** [comment]
;)
