### ISSUE TITLE
Disable dismissview

### ISSUE THREAD

**Issue by zemadara** [Morbix/CloudTagView#2]
hi,

is it possible to disable and don't display the dismiss icon ?

**Comment by Morbix** [comment]
Hi, I will check this and add this feature if need. Ok?

Enviado do meu iPhone

**Comment by Morbix** [comment]
Hi @zemadara , I've just release version 1.0.3 that solves your problem. Set the **imageIcon** property with `nil` and the text will fit properly in the tag's bounds and the dismiss event will not be fired.

**Comment by zemadara** [comment]
thank you very much
