### ISSUE TITLE
Storyboard and CloudTagView

### ISSUE THREAD

**Issue by zemadara** [Morbix/CloudTagView#3]
Hello (it's me again ...),
can i declare in my layout a UIView in CloudTagView and add tag or am I forced to declare my CloudTagView like this "let cloudView = CloudTagView()" in my code ?

**Comment by Morbix** [comment]
I think you can put a UIView in your storyboard, set the custom class to CloudTagView and declare this as an IBOutlet. It should work. But adding tags using storyboard, this is not possible and I don't even know how to do this. Sorry.

**Comment by zemadara** [comment]
Thanks and i don't want add tag in storyboard :)
