### ISSUE TITLE
Change background color

### ISSUE THREAD

**Issue by zemadara** [Morbix/CloudTagView#4]
Hi,
i would like to change the background color, to have different color in my tags, how can i do ?

**Comment by Morbix** [comment]
Hi @zemadara , I've just release 1.0.4:
- CHANGE: considering the backgroundColor's Tag;
- ADD: a tintColor's property in Tag to affect the icon and text colors. 

![screenshot2](https://raw.githubusercontent.com/Morbix/CloudTagView/master/Screenshot2.png)

**Comment by zemadara** [comment]
Perfect, you're a great man
