### ISSUE TITLE
Swift 3.0

### ISSUE THREAD

**Issue by zemadara** [Morbix/CloudTagView#8]
Hi any plan to upgrade the library to 3.0 ?

**Comment by Morbix** [comment]
@zemadara as soon as possible.

**Comment by zemadara** [comment]
hello i have worked on it and i have the CloudTagView class which compile without issues do you want this class ?

**Comment by Morbix** [comment]
Why don't you submit a Pull Request? I would love have you as a contributor.

**Comment by zemadara** [comment]
because i don't know how to do this

**Comment by Morbix** [comment]
@zemadara Fork my repository on GitHub, make your changes, make commit & push, go back to my repository, access Pull Request's tab and create a new one. Follow the default configuration and everything goes right.

It's pretty easy. ;)

**Comment by chbuie** [comment]
Hi, quick question.  Will a Swift 3.0 branch be created?

**Comment by Morbix** [comment]
Hi @chbuie , yes, this weekend will be available. Remind me. ;]

**Comment by chbuie** [comment]
Nice man, you rock!

**Comment by Morbix** [comment]
@zemadara @chbuie version 2.0.0 available with support to Swift 3.0
